# Generated by Django 3.2.6 on 2022-10-20 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('download_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebooksmodel',
            name='pdf',
            field=models.FileField(upload_to='csvs/'),
        ),
    ]
